version: '3'

services:
  db:
    container_name: "db"
    build: ./mysql
    restart: always
    tty: true
    environment:
      MYSQL_DATABASE: MOOdb
      MYSQL_USER: miguel
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: pass 
    ports:
      - "3307:3306"
    networks:
      - deploy_network
  fastapi:
    depends_on:
      - db
    build: fastapi/
    networks:
      - deploy_network
    ports: 
      - 8003:8003
    container_name: MOOback
    env_file:
      - back.env
  streamlit:
    build: streamlit-front/
    networks:
      - deploy_network
    depends_on:
      - fastapi
    ports: 
        - 8501:8501
    container_name: MOOfront
    env_file:
      - front.env

networks:
  deploy_network:
    driver: bridge