version: '3'

services:
  fastapi:
    build: fastapi/
    ports: 
      - 8001:8001
    container_name: MOOback

  streamlit:
    build: streamlit-front/
    depends_on:
      - fastapi
    ports: 
        - 8501:8501
    container_name: MOOfront
    env_file:
      - front.env
networks:
  deploy_network:
    driver: bridge